"""add widget_configs table

Revision ID: 814295300a5a
Revises: 58253cc80add
Create Date: 2026-01-24 08:13:17.183052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814295300a5a'
down_revision: Union[str, Sequence[str], None] = '58253cc80add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('widget_key', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('theme_color', sa.String(), nullable=True),
    sa.Column('bubble_icon', sa.String(), nullable=True),
    sa.Column('welcome_message', sa.String(), nullable=True),
    sa.Column('bot_name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('show_branding', sa.Boolean(), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('allowed_domains', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index(op.f('ix_widget_configs_id'), 'widget_configs', ['id'], unique=False)
    op.create_index(op.f('ix_widget_configs_widget_key'), 'widget_configs', ['widget_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widget_configs_widget_key'), table_name='widget_configs')
    op.drop_index(op.f('ix_widget_configs_id'), table_name='widget_configs')
    op.drop_table('widget_configs')
    # ### end Alembic commands ###
